### ISSUE TITLE
great project pandey!!! 🐱‍🏍 Just few issues to adjust.

### ISSUE THREAD

**Issue by digitekh2i** [Prabhakarzx/HTML-CSS-Conference-Page-Capstone#1]
1. while on mobile state on the home page, the main program section, you'd see that the texts are not fully responsive, the text goes out of its containing box. convert the pixels to its equivalent % or em.  you can use this formula: target ÷ context = result. for example... your desired font size is 24px and the context is 16px. thus 24 ÷ 16 = the result in ems >>> 1.5em. or the equivalent in %.

2. No content on the About and Ticket pages yet.

Generally, your work is awesome. 
keep it👌 

good progress so far...

**Comment by Prabhakarzx** [comment]
# Dear @digitekh2i
## Thank You so much for your detailed and informative suggestions. It helped me to improve the page and increased my knowledge base. :100: 
**All the suggestions have been applied!**
### Thank You :bouquet:
